// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TaxCalculator.Models;

#nullable disable

namespace TaxCalculator.Migrations
{
    [DbContext(typeof(TaxRateContext))]
    [Migration("20221116150942_Initial-Migration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("TaxCalculator.Models.TaxRate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("High")
                        .HasColumnType("int");

                    b.Property<int>("Low")
                        .HasColumnType("int");

                    b.Property<float>("Rate")
                        .HasColumnType("float");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("TaxRates");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            High = 49020,
                            Low = 0,
                            Rate = 15f,
                            Type = 0
                        },
                        new
                        {
                            Id = 2,
                            High = 98040,
                            Low = 49020,
                            Rate = 20.5f,
                            Type = 0
                        },
                        new
                        {
                            Id = 3,
                            High = 151978,
                            Low = 98040,
                            Rate = 26f,
                            Type = 0
                        },
                        new
                        {
                            Id = 4,
                            High = 216511,
                            Low = 151978,
                            Rate = 29f,
                            Type = 0
                        },
                        new
                        {
                            Id = 5,
                            High = 1000000000,
                            Low = 216511,
                            Rate = 33f,
                            Type = 0
                        },
                        new
                        {
                            Id = 6,
                            High = 46295,
                            Low = 0,
                            Rate = 15f,
                            Type = 1
                        },
                        new
                        {
                            Id = 7,
                            High = 92580,
                            Low = 46295,
                            Rate = 20f,
                            Type = 1
                        },
                        new
                        {
                            Id = 8,
                            High = 112655,
                            Low = 92580,
                            Rate = 24f,
                            Type = 1
                        },
                        new
                        {
                            Id = 9,
                            High = 100000000,
                            Low = 112655,
                            Rate = 25.75f,
                            Type = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
